# Generated by Django 5.2.5 on 2025-08-21 07:13

import django.core.validators
import django.db.models.deletion
import store.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('iso_3166', models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}$')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('author', models.CharField(db_index=True, max_length=255)),
                ('first_publication_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_bc', models.BooleanField(default=False)),
                ('blurb', models.TextField(blank=True, max_length=1200)),
                ('publisher', models.CharField(db_index=True, max_length=255)),
                ('edition', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('language', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=13, unique=True, validators=[store.models.validate_isbn_cleaned])),
                ('is_new', models.BooleanField(default=True)),
                ('baseprice', models.DecimalField(db_index=True, decimal_places=2, max_digits=6)),
                ('discount', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('book_format', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='store.bookformat')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.genre')),
                ('stock', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='store.stock')),
            ],
            options={
                'ordering': ['title', 'author', 'stock', '-edition'],
                'unique_together': {('title', 'author', 'publisher', 'edition', 'language', 'book_format')},
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=255)),
                ('state_province', models.CharField(blank=True, max_length=255, null=True)),
                ('city_town', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=20)),
                ('street_name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=50)),
                ('apartment_suite', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, max_length=2500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.country')),
            ],
            options={
                'ordering': ['user', 'recipient'],
                'unique_together': {('user', 'recipient', 'country', 'zip_code', 'street_name', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('when_placed', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('when_last_update', models.DateTimeField(auto_now=True, db_index=True)),
                ('deliverer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
                ('delivery_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='store.orderstatus')),
            ],
            options={
                'ordering': ['status__title', 'user'],
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_histories', to='store.order')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='store.orderstatus')),
            ],
            options={
                'ordering': ['order', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
                'unique_together': {('user', 'book')},
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.book')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='store.order')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('order', 'book')},
            },
        ),
    ]
